### ISSUE TITLE
Add 'kn source kafka list' command

### ISSUE THREAD

**Issue by navidshaikh** [knative-sandbox/kn-plugin-source-kafka#17]
Add `list` command to kafka source plugin

**Comment by maximilien** [comment]
OK... Updated the common source to latest client v0.20.0. See https://github.com/maximilien/kn-source-pkg/releases/tag/v0.6.0

**Comment by maximilien** [comment]
I will be pushing an update to solve this this week. Hopefully tomorrow. I’ll tag here.

**Comment by dsimansk** [comment]
@Kaustubh-pande FYI ^^.

**Comment by maximilien** [comment]
Hi, all, see https://github.com/maximilien/kn-source-pkg/releases/tag/v0.6.1

@dsimansk @Kaustubh-pande let me know if any issue(s) Thanks 🙏
